In [1]:
import numpy 
print(numpy.__version__)


1.21.6


In [2]:
import numpy as np
print(np.__version__)

1.21.6


In [3]:
l=[10,20,30]

In [4]:
l[0]

10

In [5]:
l[1]

20

In [6]:
#  to check whethe list is mutable   or not 
l=[10,20,30,40]

In [7]:
l.append(45)

In [8]:
l

[10, 20, 30, 40, 45]

In [9]:
l[0]=100

In [10]:
l

[100, 20, 30, 40, 45]

In [12]:

#  vector operations 
l=[10,20,30]


l+2

TypeError: can only concatenate list (not "int") to list

In [15]:
l=[10,20,30]
l1=[]
for i in l:
    l1.append(i+2)

l1

[12, 22, 32]

In [13]:
a= np.array([10,20,30])
a+2

array([12, 22, 32])

In [16]:
l=["eswar",10,20,34.5]

In [17]:
l

['eswar', 10, 20, 34.5]

In [18]:
#  arrays consumes less memory 
#  list 

l1=[10,20,30,40,40,56,78,98,67,10,20,30,40,40,56,78,98,67,10,20,30,40,40,56,78,98,67]
a=np.array(l1)
l1

[10,
 20,
 30,
 40,
 40,
 56,
 78,
 98,
 67,
 10,
 20,
 30,
 40,
 40,
 56,
 78,
 98,
 67,
 10,
 20,
 30,
 40,
 40,
 56,
 78,
 98,
 67]

In [19]:
a

array([10, 20, 30, 40, 40, 56, 78, 98, 67, 10, 20, 30, 40, 40, 56, 78, 98,
       67, 10, 20, 30, 40, 40, 56, 78, 98, 67])

In [20]:

import sys
print("size consumed by array ",sys.getsizeof(a))
print("size consumed by list ",sys.getsizeof(l1))

size consumed by array  212
size consumed by list  280


In [21]:

#  arrrays super fast 
import time
size = 1000000
l1=range(size)
l2= range(size)
a1=np.arange(size)
a2=np.arange(size)

start= time.time()
result = [(x+y) for x,y in zip(l1,l2)]   # list comphehension 
print("Python list addition time taken ", (time.time()-start)*1000)


start= time.time()
result =    a1 + a2 
print("Numpy array addition time taken ", (time.time()-start)*1000)

Python list addition time taken  103.41358184814453
Numpy array addition time taken  14.996767044067383


In [23]:
a= np.array([1,10.5,67.9,87,45])


In [24]:
a

array([ 1. , 10.5, 67.9, 87. , 45. ])

In [25]:

#  creating an array by using array package 
import array 

a=  array.array('i',[10,20,30,40])

print("array elements ",a)
print("type ",type(a))
for i in range(len(a)):
    print(a[i])
    
#  numpy array ndarray 

array elements  array('i', [10, 20, 30, 40])
type  <class 'array.array'>
10
20
30
40


In [27]:
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [28]:
# creating 1d array 
l=[10,20,30]
print(" type  ",type(l))

a=np.array(l)
print(type(a))
for i in range(len(a)):
    print(a[i])

 type   <class 'list'>
<class 'numpy.ndarray'>
10
20
30


In [29]:
print("dimensions of array  ",a.ndim)
print("data type of array  ",a.dtype)
print("size of array  ",a.size)
print("shape of array  ",a.shape)

dimensions of array   1
data type of array   int32
size of array   3
shape of array   (3,)


In [30]:
t=("eswar","rakesh","vishnu")
a=np.array(t)
print(type(a))
for i in range(len(a)):
    print(a[i])
print("dimensions of array  ",a.ndim)
print("data type of array  ",a.dtype)
print("size of array  ",a.size)
print("shape of array  ",a.shape)

<class 'numpy.ndarray'>
eswar
rakesh
vishnu
dimensions of array   1
data type of array   <U6
size of array   3
shape of array   (3,)


In [31]:
t=("eswar",27,97.6)
a=np.array(t)
print(type(a))
for i in range(len(a)):
    print(a[i])
print("dimensions of array  ",a.ndim)
print("data type of array  ",a.dtype)
print("size of array  ",a.size)
print("shape of array  ",a.shape)

<class 'numpy.ndarray'>
eswar
27
97.6
dimensions of array   1
data type of array   <U32
size of array   3
shape of array   (3,)


In [32]:
a

array(['eswar', '27', '97.6'], dtype='<U32')

In [ ]:
# type casting 


In [33]:
#  creating 2d array 

#  [[]]

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(type(a))
for i in range(len(a)):
    print(a[i])
print("dimensions of array  ",a.ndim)
print("data type of array  ",a.dtype)
print("size of array  ",a.size)
print("shape of array  ",a.shape)

<class 'numpy.ndarray'>
[10 20 30]
[40 50 60]
[70 80 90]
dimensions of array   2
data type of array   int32
size of array   9
shape of array   (3, 3)


In [34]:
t=(1,27,97.6,67.8,100,34,23)
a=np.array(t)
print(type(a))
for i in range(len(a)):
    print(a[i])
print("dimensions of array  ",a.ndim)
print("data type of array  ",a.dtype)
print("size of array  ",a.size)
print("shape of array  ",a.shape)

<class 'numpy.ndarray'>
1.0
27.0
97.6
67.8
100.0
34.0
23.0
dimensions of array   1
data type of array   float64
size of array   7
shape of array   (7,)


In [35]:
t=(1,27,97.6,67.8,100,34,23)
a=np.array(t,dtype=int)
print(type(a))
for i in range(len(a)):
    print(a[i])
print("dimensions of array  ",a.ndim)
print("data type of array  ",a.dtype)
print("size of array  ",a.size)
print("shape of array  ",a.shape)

<class 'numpy.ndarray'>
1
27
97
67
100
34
23
dimensions of array   1
data type of array   int32
size of array   7
shape of array   (7,)


In [36]:
t=(1,27,97.6,67.8,100,34,23)
a=np.array(t,dtype=str)
print(type(a))
for i in range(len(a)):
    print(a[i])
print("dimensions of array  ",a.ndim)
print("data type of array  ",a.dtype)
print("size of array  ",a.size)
print("shape of array  ",a.shape)

<class 'numpy.ndarray'>
1
27
97.6
67.8
100
34
23
dimensions of array   1
data type of array   <U4
size of array   7
shape of array   (7,)


In [37]:
a

array(['1', '27', '97.6', '67.8', '100', '34', '23'], dtype='<U4')

In [38]:
#  range  
a=range(10)  # start = 0  step = 1

for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [40]:
a=range(5,20)  # start = 0  step = 1

for i in a:
    print(i,end=" ")

5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [41]:
a=range(5,20,2)  # start = 0  step = 1

for i in a:
    print(i,end=" ")

5 7 9 11 13 15 17 19 

In [ ]:
# generating list of values within given range 

In [42]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [43]:
a= np.arange(10)

In [44]:
type(a)

numpy.ndarray

In [ ]:
#  start = 1
# stop  n-1  
# step  = 1


In [45]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
print("dimensions of array  ",a.ndim)
print("data type of array  ",a.dtype)
print("size of array  ",a.size)
print("shape of array  ",a.shape)

dimensions of array   1
data type of array   int32
size of array   10
shape of array   (10,)


In [47]:
a=np.arange(1,60,2)

In [48]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])

In [49]:
a=np.arange(1,60,2,dtype=float)

In [50]:
a

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59.])

In [51]:
a.reshape(10,3)

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.],
       [13., 15., 17.],
       [19., 21., 23.],
       [25., 27., 29.],
       [31., 33., 35.],
       [37., 39., 41.],
       [43., 45., 47.],
       [49., 51., 53.],
       [55., 57., 59.]])

###  Linpspace 

In [3]:
import numpy as np

In [4]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [5]:
import numpy as np

In [6]:
l1 = np.linspace(1,8)

In [10]:
l1.shape

(50,)

In [11]:
l1

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ,
       3.14285714, 3.28571429, 3.42857143, 3.57142857, 3.71428571,
       3.85714286, 4.        , 4.14285714, 4.28571429, 4.42857143,
       4.57142857, 4.71428571, 4.85714286, 5.        , 5.14285714,
       5.28571429, 5.42857143, 5.57142857, 5.71428571, 5.85714286,
       6.        , 6.14285714, 6.28571429, 6.42857143, 6.57142857,
       6.71428571, 6.85714286, 7.        , 7.14285714, 7.28571429,
       7.42857143, 7.57142857, 7.71428571, 7.85714286, 8.        ])

In [9]:
a=np.arange(1,60)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [12]:
l1 = np.linspace(1,8,40)

In [13]:
l1

array([1.        , 1.17948718, 1.35897436, 1.53846154, 1.71794872,
       1.8974359 , 2.07692308, 2.25641026, 2.43589744, 2.61538462,
       2.79487179, 2.97435897, 3.15384615, 3.33333333, 3.51282051,
       3.69230769, 3.87179487, 4.05128205, 4.23076923, 4.41025641,
       4.58974359, 4.76923077, 4.94871795, 5.12820513, 5.30769231,
       5.48717949, 5.66666667, 5.84615385, 6.02564103, 6.20512821,
       6.38461538, 6.56410256, 6.74358974, 6.92307692, 7.1025641 ,
       7.28205128, 7.46153846, 7.64102564, 7.82051282, 8.        ])

In [14]:
l1.shape

(40,)

In [18]:


#  iron rod    
#   40   -  10 cm 

l1=np.linspace(0,10,20)

In [19]:
l1

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that pas

In [25]:
np.full((3,3),fill_value=2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [26]:
np.full((3,3),fill_value=7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [27]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_functi

In [28]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [29]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [31]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[1.

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.identity((3,4))   #  it wont accept other than square matrix 

TypeError: 'tuple' object cannot be interpreted as an integer

In [37]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.empty((5,6))

array([[1.18284810e-311, 1.01283457e-321, 0.00000000e+000,
        0.00000000e+000, 1.78020848e-306, 1.16097020e-028],
       [8.26219736e-072, 2.17002273e-028, 4.66250626e-062,
        1.04917183e-153, 5.23081515e-143, 1.86924404e-051],
       [4.01521875e-057, 8.67807548e-067, 3.92690746e-061,
        1.70098498e+256, 5.49109388e-143, 1.06396443e+224],
       [3.96041428e+246, 1.16318408e-028, 2.90254339e+180,
        9.06147602e-043, 2.65140322e-032, 3.63977907e+175],
       [1.01848862e+248, 1.16096643e-028, 9.80058441e+252,
        7.50189709e+247, 1.14484251e+243, 2.59903827e-144]])

###  data types 

In [42]:
import sys

a=np.array([10,20,30,40])  #  by deafult int32 

print("size of int 32 ",sys.getsizeof(a))

a=np.array([10,20,30,40],dtype='int8')  #  by deafult int32 

print("size of int 8 ",sys.getsizeof(a))

size of int 32  120
size of int 8  108


In [43]:

a=np.array([10,20,30,40]) 
b=a.astype('float64')
print(a)
print(b)

print(" data type    a   ",a.dtype)
print(" data type    b   ",b.dtype)
print("size of int  ",sys.getsizeof(a))
print("size of float ",sys.getsizeof(b))

[10 20 30 40]
[10. 20. 30. 40.]
 data type    a    int32
 data type    b    float64
size of int   120
size of float  136


In [44]:
a=np.array([10,20,30,40]) 
b=np.float64(a)
print(a)
print(b)

print(" data type    a   ",a.dtype)
print(" data type    b   ",b.dtype)
print("size of int  ",sys.getsizeof(a))
print("size of float ",sys.getsizeof(b))

[10 20 30 40]
[10. 20. 30. 40.]
 data type    a    int32
 data type    b    float64
size of int   120
size of float  136


In [45]:

import numpy as np 
a=np.array([11,19,24,35])

b=a.view()

print("original array  a",a)
print("original array  b",b)
a[0]=  888
print("*******************************")
print("After a  array  change",a)
print("after  a change array  b",b)
print("*******************************")
b[-1]=999
print("After b  array  change",a)
print("after  b change array  b",b)

original array  a [11 19 24 35]
original array  b [11 19 24 35]
*******************************
After a  array  change [888  19  24  35]
after  a change array  b [888  19  24  35]
*******************************
After b  array  change [888  19  24 999]
after  b change array  b [888  19  24 999]


In [46]:
import numpy as np 
a=np.array([11,19,24,35])

b=a.copy()

print("original array  a",a)
print("original array  b",b)
a[0]=  888
print("*******************************")
print("After a  array  change",a)
print("after  a change array  b",b)
print("*******************************")
b[-1]=999
print("After b  array  change",a)
print("after  b change array  b",b)

original array  a [11 19 24 35]
original array  b [11 19 24 35]
*******************************
After a  array  change [888  19  24  35]
after  a change array  b [11 19 24 35]
*******************************
After b  array  change [888  19  24  35]
after  b change array  b [ 11  19  24 999]


### indexing 

In [47]:
import numpy as np 
a=np.array([11,19,24,35])

print(a[1])

19


In [48]:
print(a[2])

24


In [49]:
import numpy as np 
#     -4   -3   -2    -1
a=np.array([11,19,24,35])

#  negative 
print(a[-1])

35


In [50]:
print(a[-2])

24


In [51]:
a=np.array([[10,20,30,40],[6,5,4,1],[6,9,2,4]])

In [52]:
a

array([[10, 20, 30, 40],
       [ 6,  5,  4,  1],
       [ 6,  9,  2,  4]])

In [ ]:
a[row_index][col_index]

In [53]:
a[0][0]

10

In [54]:
a[1][0]

6

In [55]:
a[-2][-2]

4

In [56]:
a[-1][-3]

9

In [57]:

#  

a= np.arange(10,165,4)

In [58]:
a

array([ 10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,
        62,  66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106, 110,
       114, 118, 122, 126, 130, 134, 138, 142, 146, 150, 154, 158, 162])

In [59]:
a[0]

10

In [60]:
a[1]

14

In [ ]:
a[start: endindex]

In [61]:
a[5:10]

array([30, 34, 38, 42, 46])

In [62]:
a[5:11]

array([30, 34, 38, 42, 46, 50])

In [63]:
a[:10]

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [64]:
a[10:]

array([ 50,  54,  58,  62,  66,  70,  74,  78,  82,  86,  90,  94,  98,
       102, 106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150,
       154, 158, 162])

In [65]:
a[:]

array([ 10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,
        62,  66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106, 110,
       114, 118, 122, 126, 130, 134, 138, 142, 146, 150, 154, 158, 162])

In [66]:
a[1::2]

array([ 14,  22,  30,  38,  46,  54,  62,  70,  78,  86,  94, 102, 110,
       118, 126, 134, 142, 150, 158])

In [67]:
a[0::2]

array([ 10,  18,  26,  34,  42,  50,  58,  66,  74,  82,  90,  98, 106,
       114, 122, 130, 138, 146, 154, 162])

In [68]:
#  access all the elements 

a[::-1]

array([162, 158, 154, 150, 146, 142, 138, 134, 130, 126, 122, 118, 114,
       110, 106, 102,  98,  94,  90,  86,  82,  78,  74,  70,  66,  62,
        58,  54,  50,  46,  42,  38,  34,  30,  26,  22,  18,  14,  10])

In [69]:
a=np.array([[1,2,3,4,4,5,6],[10,20,33,41,41,56,67],[1,12,13,14,14,15,6]])

In [70]:
a

array([[ 1,  2,  3,  4,  4,  5,  6],
       [10, 20, 33, 41, 41, 56, 67],
       [ 1, 12, 13, 14, 14, 15,  6]])

In [71]:
print(a[1:3,0:3])

[[10 20 33]
 [ 1 12 13]]


In [72]:
print(a[1,0:3])

[10 20 33]


In [73]:
print(a[:,1])

[ 2 20 12]


In [75]:
print(a[1:3,1::2])

[[20 41 56]
 [12 14 15]]


In [76]:
a

array([[ 1,  2,  3,  4,  4,  5,  6],
       [10, 20, 33, 41, 41, 56, 67],
       [ 1, 12, 13, 14, 14, 15,  6]])

In [77]:
a[:,-1]

array([ 6, 67,  6])

In [79]:
a[:,-3:-1]

array([[ 4,  5],
       [41, 56],
       [14, 15]])

In [80]:
a[-2:,-3:-1]

array([[41, 56],
       [14, 15]])

In [82]:
a=np.arange(10,101,2)

In [83]:
a

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

In [84]:
#  1   12   18  23 

# 1st way  ndarray 
indexes = np.array([1,12,18,23])
indexes

array([ 1, 12, 18, 23])

In [85]:
a[indexes]

array([12, 34, 46, 56])

In [86]:
# 2nd way 
l=[1,12,18,23]
a[l]

array([12, 34, 46, 56])

In [88]:

#  
a=np.array([[1,2,3,4,5],[11,21,31,41,51],[12,22,32,42,52]])

In [89]:
a

array([[ 1,  2,  3,  4,  5],
       [11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52]])

In [90]:
a[[0,1,2],[0,1,3]]  #  (0,0),(1,1),(2,3) 

array([ 1, 21, 42])

In [92]:
a[[0,1,2],[0,1,4]]

array([ 1, 21, 52])

In [93]:
a[[0,1],[0,1,4]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [94]:
a[[0,1],[0,1,10]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

### condion based selection 

In [1]:

# select elements   elements  > 25  

import numpy as np
a= np.array([20,30,22,35,46,19])

a[a>25]

array([30, 35, 46])

In [2]:
a[a<25]

array([20, 22, 19])

In [3]:
import numpy as np
a= np.array([-1,10,1,-10,-2,-5,6,7])
a[a<0]

array([ -1, -10,  -2,  -5])

In [5]:
import numpy as np
a= np.array([10,11,12,45,46,78,90,99])
a[a%2==0]
             
# a%2==0    

array([10, 12, 46, 78, 90])

In [6]:
a=np.arange(1,31).reshape(5,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [7]:
# select numbers which are divisible  by 2 and 3

b= np.logical_and(a%2==0,a%3==0)

In [8]:
b

array([[False, False, False, False, False,  True],
       [False, False, False, False, False,  True],
       [False, False, False, False, False,  True],
       [False, False, False, False, False,  True],
       [False, False, False, False, False,  True]])

In [9]:
a[b]

array([ 6, 12, 18, 24, 30])

In [10]:
a[(a%2==0)&(a%3==0)]

array([ 6, 12, 18, 24, 30])

In [11]:

b= np.logical_or(a%2==0,a%3==0)


In [12]:
b

array([[False,  True,  True,  True, False,  True],
       [False,  True,  True,  True, False,  True],
       [False,  True,  True,  True, False,  True],
       [False,  True,  True,  True, False,  True],
       [False,  True,  True,  True, False,  True]])

In [13]:
a[b]

array([ 2,  3,  4,  6,  8,  9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 26,
       27, 28, 30])

In [14]:
a[(a%2==0)|(a%3==0)]

array([ 2,  3,  4,  6,  8,  9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 26,
       27, 28, 30])

In [15]:
b= np.logical_not(a%2==0)

In [16]:
b

array([[ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [17]:
a[b]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [18]:
#  (2 , 2 , 4)
l=  [[[1,2,3,4],[5,6,7,8]],[[11,12,13,14],[15,16,17,18]]]

a= np.array(l)

In [19]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18]]])

In [20]:
a.shape

(2, 2, 4)

In [21]:
a[1][1][1]

16

In [22]:
#  through index only one elements  
a[-1][-1][-1]

18

In [ ]:
a[start:end]
a[start:end,start:end]
a[start:end,start:end,start:end]
a[start:end,start:end,start:end,start:end,start:end,start:end]

In [23]:
l=  [[[1,2,3,4],[5,6,7,8]],[[11,12,13,14],[15,16,17,18]],
     [[21,22,23,24],[25,26,27,28]]]

a= np.array(l)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28]]])

In [ ]:

#  second array  and third array 
#    2   row 
#    2 to 4th columns  

In [27]:
a[1:,1,1:]

array([[16, 17, 18],
       [26, 27, 28]])

In [28]:
a=np.arange(45).reshape(3,3,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [29]:
a[:,:,:]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [30]:
# What is price of gold in Chennai market on Tuesday 
a[1][0][1]

16

In [31]:
# 2.	  Price of gold and silver from Monday to thurs day   
#in hyderbad ,chennai

a[0:2,0:2,0:4]

array([[[ 0,  1,  2,  3],
        [ 5,  6,  7,  8]],

       [[15, 16, 17, 18],
        [20, 21, 22, 23]]])

In [32]:
#  hyd gold values   
a[0,0,:]

array([0, 1, 2, 3, 4])

In [34]:
a= np.arange(10,40)
for i in a:
    
    i=i+1000
    print(i,end=" ")

10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 

In [35]:
a=[[1,2,3,4],[5,6,7,8],[15,16,17,18]]
a

[[1, 2, 3, 4], [5, 6, 7, 8], [15, 16, 17, 18]]

In [37]:
#a[i][j]
for i in a:
    for j in i:
        print(j,end=" ")
    

1 2 3 4 5 6 7 8 15 16 17 18 

In [38]:
a=[[[1,2],[5,6],[15,16]],[[11,12],[15,16],[25,26]]]
a

[[[1, 2], [5, 6], [15, 16]], [[11, 12], [15, 16], [25, 26]]]

In [39]:
for i in a:   #  which array 
    for j in i:  #  which row
        for k in j:  #  which column 
            print(k,end=" ")
            
            
#Note 
#  time comlexity increases

1 2 5 6 15 16 11 12 15 16 25 26 

In [42]:
a=np.arange(10,40)
for i in np.nditer(a):
    print(i,end=" ")

10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 

In [43]:
a=[[1,2,3,4],[5,6,7,8],[15,16,17,18]]
a

[[1, 2, 3, 4], [5, 6, 7, 8], [15, 16, 17, 18]]

In [44]:
for i in np.nditer(a):
    print(i,end=" ")

(array(1), array(5), array(15)) (array(2), array(6), array(16)) (array(3), array(7), array(17)) (array(4), array(8), array(18)) 

In [45]:
a=[[[1,2],[5,6],[15,16]],[[11,12],[15,16],[25,26]]]
a

[[[1, 2], [5, 6], [15, 16]], [[11, 12], [15, 16], [25, 26]]]

In [46]:
for i in np.nditer(a):
    print(i,end=" ")

(array(1), array(11)) (array(2), array(12)) (array(5), array(15)) (array(6), array(16)) (array(15), array(25)) (array(16), array(26)) 

In [47]:
help(np.nditer)

Help on class nditer in module numpy:

class nditer(builtins.object)
 |  nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)
 |  
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |  
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |  
 |  flags : sequence of str, optional
 |        Flags to control the behavior of the iterator.
 |  
 |        * ``buffered`` enables buffering when required.
 |        * ``c_index`` causes a C-order index to be tracked.
 |        * ``f_index`` causes a Fortran-order index to be tracked.
 |        * ``multi_index`` causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * ``common_dtype`` causes all the operands to be converted to

In [55]:
a=np.array([[1,2,3,4],[5,6,7,8],[15,16,17,18]])
for i in np.nditer(a,op_dtypes=['float']):
    print(i,end=" ")

TypeError: Iterator operand required copying or buffering, but neither copying nor buffering was enabled

In [56]:
a=np.array([[1,2,3,4],[5,6,7,8],[15,16,17,18]])
for i in np.nditer(a,flags = ['buffered'] ,op_dtypes=['float']):
    print(i,end=" ")

1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 15.0 16.0 17.0 18.0 

In [57]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [15, 16, 17, 18]])

In [58]:
a=np.array([10,20,30,40,50])

for pos,elem in np.ndenumerate(a):
    print("elemeant ",elem ," present as  ",pos)

elemeant  10  present as   (0,)
elemeant  20  present as   (1,)
elemeant  30  present as   (2,)
elemeant  40  present as   (3,)
elemeant  50  present as   (4,)


In [59]:
a=np.array([[1,2,3,4],[5,6,7,8],[15,16,17,18]])
for pos,elem in np.ndenumerate(a):
    print("elemeant ",elem ," present as  ",pos)

elemeant  1  present as   (0, 0)
elemeant  2  present as   (0, 1)
elemeant  3  present as   (0, 2)
elemeant  4  present as   (0, 3)
elemeant  5  present as   (1, 0)
elemeant  6  present as   (1, 1)
elemeant  7  present as   (1, 2)
elemeant  8  present as   (1, 3)
elemeant  15  present as   (2, 0)
elemeant  16  present as   (2, 1)
elemeant  17  present as   (2, 2)
elemeant  18  present as   (2, 3)


In [1]:
a=5 
b=2
print(a/b)
print(a//b)

2.5
2


In [2]:
print(a%b)

1


In [4]:
#1D arrays 
import numpy as np
a= np.array([10,20,31])
print("add ",a+2)
print("sub ",a-2)
print("div ",a/2)
print("floor ",a//2)
print("modulo ",a%2)
print("a**2  ", a**2)

add  [12 22 33]
sub  [ 8 18 29]
div  [ 5.  10.  15.5]
floor  [ 5 10 15]
modulo  [0 0 1]
a**2   [100 400 961]


In [5]:

# 2d array 
import numpy as np
a= np.array([[10,20,31],[5,4,6],[10,21,11]])
print("add ",a+2)
print("sub ",a-2)
print("div ",a/2)
print("floor ",a//2)
print("modulo ",a%2)
print("a**2  ", a**2)

add  [[12 22 33]
 [ 7  6  8]
 [12 23 13]]
sub  [[ 8 18 29]
 [ 3  2  4]
 [ 8 19  9]]
div  [[ 5.  10.  15.5]
 [ 2.5  2.   3. ]
 [ 5.  10.5  5.5]]
floor  [[ 5 10 15]
 [ 2  2  3]
 [ 5 10  5]]
modulo  [[0 0 1]
 [1 0 0]
 [0 1 1]]
a**2   [[100 400 961]
 [ 25  16  36]
 [100 441 121]]


In [6]:
import numpy as np
a= np.array([10,20,31])
b = np.array([12,13,34])
print("add ",a+b)
print("sub ",a-b)
print("div ",a/b)
print("floor ",a//b)
print("modulo ",a%b)
print("a**2  ", a**b)

add  [22 33 65]
sub  [-2  7 -3]
div  [0.83333333 1.53846154 0.91176471]
floor  [0 1 0]
modulo  [10  7 31]
a**2   [-727379968 1409286144 1725480897]


In [7]:
import numpy as np
a= np.array([[10,20,31],[5,4,6],[10,21,11]])
b = np.array([[11,4,10],[5,4,6],[10,5,6]])
print("add ",a+b)
print("sub ",a-b)
print("div ",a/b)
print("floor ",a//b)
print("modulo ",a%b)
print("a**2  ", a**b)

add  [[21 24 41]
 [10  8 12]
 [20 26 17]]
sub  [[-1 16 21]
 [ 0  0  0]
 [ 0 16  5]]
div  [[0.90909091 5.         3.1       ]
 [1.         1.         1.        ]
 [1.         4.2        1.83333333]]
floor  [[0 5 3]
 [1 1 1]
 [1 4 1]]
modulo  [[10  0  1]
 [ 0  0  0]
 [ 0  1  5]]
a**2   [[ 1215752192      160000 -1796951359]
 [       3125         256       46656]
 [ 1410065408     4084101     1771561]]


In [8]:
import numpy as np
a= np.array([[10,20,31],[5,4,6],[10,21,11]])
b = np.array([[4,10],[4,6],[5,6]])
print("add ",a+b)
print("sub ",a-b)
print("div ",a/b)
print("floor ",a//b)
print("modulo ",a%b)
print("a**2  ", a**b)

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [9]:
import numpy as np
a= np.array([10,20,31])
b = np.array([12,13,34,5,6])
print("add ",a+b)
print("sub ",a-b)
print("div ",a/b)
print("floor ",a//b)
print("modulo ",a%b)
print("a**2  ", a**b)

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [10]:
import numpy as np
a= np.array([10,20,31])
b = np.array([12,13,34])
print("add ",np.add(a,b))
print("sub ",np.subtract(a,b))

add  [22 33 65]
sub  [-2  7 -3]


In [11]:

import numpy as np
a= np.array([10,20,31])
b = np.array([12,13,34,6,7,9])
print("add ",np.add(a,b))
print("sub ",np.subtract(a,b))

ValueError: operands could not be broadcast together with shapes (3,) (6,) 

In [12]:
import numpy as np
a= np.array([10,20,31])
b = np.array([12,13,34])
print("add ",np.add(a,b))
print("sub ",np.subtract(a,b))

add  [22 33 65]
sub  [-2  7 -3]


In [13]:
import numpy as np
a= np.array([10,20,31])
b=np.array([40])
print(a.shape)
print(b.shape)

(3,)
(1,)


In [14]:
print(a+b)

[50 60 71]


In [ ]:
[10,20,31]
[40 40  40]

50  60  71  

In [15]:
a=np.array([[2,3],[1,2],[4,2]])
b=np.array([[1,2]])
print(a+b)

2 * 2  
1  *  2

[[3 5]
 [2 4]
 [5 4]]


In [ ]:
[[2,3],[1,2],[4,2]]
[1,2]  [1,2]  [1,2] 

3  5   2  4    5  4

In [16]:
a=np.array([[2,3],[1,2],[4,2]])
b=np.array([[1,2,3]])
print(a+b)


ValueError: operands could not be broadcast together with shapes (3,2) (1,3) 

In [17]:
a=np.array([[2,3],[1,2],[4,2]])
b=np.array([1,2])
print(a+b)


[[3 5]
 [2 4]
 [5 4]]


In [18]:
a=np.array([[[2,3],[1,2],[4,2]],[[2,3],[1,2],[4,2]]])  #  2  3  2 
b=np.array([1,2])
print(a+b)


[[[3 5]
  [2 4]
  [5 4]]

 [[3 5]
  [2 4]
  [5 4]]]


In [19]:
a=np.array([[[2,3],[1,2],[4,2]],[[2,3],[1,2],[4,2]]])  #  2  3  2 
b=np.array([1,2,4])
print(a+b)


ValueError: operands could not be broadcast together with shapes (2,3,2) (3,) 

In [20]:
help(np.ndarray.flatten)

Help on method_descriptor:

flatten(...)
    a.flatten(order='C')
    
    Return a copy of the array collapsed into one dimension.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        'C' means to flatten in row-major (C-style) order.
        'F' means to flatten in column-major (Fortran-
        style) order. 'A' means to flatten in column-major
        order if `a` is Fortran *contiguous* in memory,
        row-major order otherwise. 'K' means to flatten
        `a` in the order the elements occur in memory.
        The default is 'C'.
    
    Returns
    -------
    y : ndarray
        A copy of the input array, flattened to one dimension.
    
    See Also
    --------
    ravel : Return a flattened array.
    flat : A 1-D flat iterator over the array.
    
    Examples
    --------
    >>> a = np.array([[1,2], [3,4]])
    >>> a.flatten()
    array([1, 2, 3, 4])
    >>> a.flatten('F')
    array([1, 3, 2, 4])



In [21]:
help(np.flatten)

AttributeError: module 'numpy' has no attribute 'flatten'

In [22]:

a=np.arange(6).reshape(3,2)
b=a.flatten()
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [23]:
a=np.arange(12).reshape(2,3,2)
b=a.flatten()
print(a)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
a=np.arange(6).reshape(3,2)
b=a.flatten()
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [25]:
a[0,0]=88

In [26]:
a

array([[88,  1],
       [ 2,  3],
       [ 4,  5]])

In [27]:
b

array([0, 1, 2, 3, 4, 5])

In [28]:
b[2]=99

In [29]:
b

array([ 0,  1, 99,  3,  4,  5])

In [30]:
a

array([[88,  1],
       [ 2,  3],
       [ 4,  5]])

In [31]:
help(np.ravel)

Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

In [35]:
a=np.arange(24).reshape(2,3,4)
b=a.ravel()
print(a)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [36]:
b[0]=88

In [37]:
b

array([88,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
a

array([[[88,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
a[0][0][1]=99

In [40]:
a

array([[[88, 99,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
b

array([88, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [42]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
a=np.arange(1,11)
b=np.reshape(a,(5,2))

In [44]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
a[0]=66

In [47]:
a

array([66,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
b

array([[66,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [50]:
a=np.arange(1,25)
b=a.reshape((2,3,4))
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [52]:
a=np.arange(1,11)
b=np.reshape(a,(5,2))
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [53]:
a=np.arange(1,11)
b=np.reshape(a,(5,-1))
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [54]:
a=np.arange(1,11)
b=np.reshape(a,(-1,2))
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [55]:
a=np.arange(1,11)
b=np.reshape(a,(-1,-1))
b

ValueError: can only specify one unknown dimension

In [56]:
a=np.arange(1,11)
b=np.resize(a,(5,2))

In [57]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [63]:
a[0]=99

In [64]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [61]:
c=np.arange(1,11)
d=np.reshape(a,(5,2))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [76]:
c[0]=99

In [77]:
d

array([[99,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [68]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [92]:
a=np.arange(1,11)
b=np.resize(a,(5,2))
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [93]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [95]:
a[0]=99

In [96]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [79]:

a=np.arange(1,11)
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [80]:
a[0]=99

In [81]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [88]:
a=np.arange(1,11)
b=a.resize(5,2)
b

In [89]:
b

In [90]:
a[0]=99

In [91]:
a

array([[99, 99],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [1]:
import numpy as np

In [2]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [3]:
a=np.array([70,20,25,45,16,17,13,46])

In [4]:
a

array([70, 20, 25, 45, 16, 17, 13, 46])

In [5]:
sorted_array = np.sort(a)
print("original array \n",a)
print("sorted  array \n",sorted_array)

original array 
 [70 20 25 45 16 17 13 46]
sorted  array 
 [13 16 17 20 25 45 46 70]


In [6]:
a=np.array([70,20,25,45,16,17,13,46])
sorted_array = np.sort(a)[::-1]
print("original array \n",a)
print("sorted  array \n",sorted_array)

original array 
 [70 20 25 45 16 17 13 46]
sorted  array 
 [70 46 45 25 20 17 16 13]


In [7]:
#  alphabeticccal order
a=np.array(['eswar','rakesh','vishnu','sreenivas','danvith ram'])
ascending = np.sort(a)
print("original array \n",a)
print("sorted  array \n",ascending)

original array 
 ['eswar' 'rakesh' 'vishnu' 'sreenivas' 'danvith ram']
sorted  array 
 ['danvith ram' 'eswar' 'rakesh' 'sreenivas' 'vishnu']


In [8]:
#  alphabeticccal order
a=np.array(['eswar','rakesh','vishnu','sreenivas','danvith ram'])
descending = np.sort(a)[::-1]
print("original array \n",a)
print("sorted  array \n",descending)

original array 
 ['eswar' 'rakesh' 'vishnu' 'sreenivas' 'danvith ram']
sorted  array 
 ['vishnu' 'sreenivas' 'rakesh' 'eswar' 'danvith ram']


In [10]:

#sname   age  height 
#  structured array  
dtype = [('name','S10'),('height',float),('age',int)]
values = [('eswar','5.6',27),('rakesh','5.8',28),('danvith','5.1',10)]
a=np.array(values,dtype=dtype)
a

array([(b'eswar', 5.6, 27), (b'rakesh', 5.8, 28), (b'danvith', 5.1, 10)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [11]:
sort_by_height = np.sort(a,order='height')
sort_by_age = np.sort(a,order='age')
print('sort by height \n',sort_by_height)
print('sort by age \n',sort_by_age)

sort by height 
 [(b'danvith', 5.1, 10) (b'eswar', 5.6, 27) (b'rakesh', 5.8, 28)]
sort by age 
 [(b'danvith', 5.1, 10) (b'eswar', 5.6, 27) (b'rakesh', 5.8, 28)]


In [12]:
dtype = [('name','S10'),('height',float),('age',int)]
values = [('eswar','5.6',27),('rakesh','5.8',28),('danvith','5.1',10),
         ('ram','5.1',9)]
a=np.array(values,dtype=dtype)
sort_by_height = np.sort(a,order='height')
print('sort by height \n',sort_by_height)

sort by height 
 [(b'danvith', 5.1, 10) (b'ram', 5.1,  9) (b'eswar', 5.6, 27)
 (b'rakesh', 5.8, 28)]


In [13]:
dtype = [('name','S10'),('height',float),('age',int)]
values = [('eswar','5.6',27),('rakesh','5.8',28),('danvith','5.1',10),
         ('ram','5.1',9)]
a=np.array(values,dtype=dtype)
sort_by_height = np.sort(a,order=['height','age'])
print('sort by height \n',sort_by_height)

sort by height 
 [(b'ram', 5.1,  9) (b'danvith', 5.1, 10) (b'eswar', 5.6, 27)
 (b'rakesh', 5.8, 28)]


In [14]:
import numpy as np
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y

In [15]:
a=np.array([3,7,9,6,7,5,11,13,19,7])
b=np.where(a==7)
print(b)

(array([1, 4, 9], dtype=int64),)


In [ ]:
0  1     4            9 
[3,7,9,6,7,5,11,13,19,7]

In [16]:
a=np.array([3,7,9,6,7,5,11,13,19,7,20,24,25])
b=np.where(a%2!=0)
print(b)

(array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 12], dtype=int64),)


In [17]:
a=np.array([3,7,9,6,7,5,11,13,19,7,20,24,25])
b=np.where(a%2==0)
print(b)

(array([ 3, 10, 11], dtype=int64),)


In [18]:
a[b]

array([ 6, 20, 24])

In [19]:
a[a%2==0]

array([ 6, 20, 24])

In [20]:
a=np.array([3,7,9,6,7,5,11,13,19,7,20,24,25])
b=np.where(a%2==0,888,999)
b

array([999, 999, 999, 888, 999, 999, 999, 999, 999, 999, 888, 888, 999])

In [21]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
#  which are divisible by 5 
np.where(a%5==0)

(array([0, 1, 3], dtype=int64), array([0, 2, 1], dtype=int64))

In [ ]:
array([0, 1, 3], dtype=int64), array([0, 2, 1]
        row                             column 
                                     
    0   0 
    1   2
    3   1                                  
        0   1   2    
    ([[ 0,  1,  2],    0 
       [ 3,  4,  5],   1
       [ 6,  7,  8],   2
       [ 9, 10, 11]])  3  
                                      

In [23]:
np.where(a%5==0,999,a)

array([[999,   1,   2],
       [  3,   4, 999],
       [  6,   7,   8],
       [  9, 999,  11]])

In [24]:
help(np.searchsorted)

Help on function searchsorted in module numpy:

searchsorted(a, v, side='left', sorter=None)
    Find indices where elements should be inserted to maintain order.
    
    Find the indices into a sorted array `a` such that, if the
    corresponding elements in `v` were inserted before the indices, the
    order of `a` would be preserved.
    
    Assuming that `a` is sorted:
    
    ======  ============================
    `side`  returned index `i` satisfies
    ======  ============================
    left    ``a[i-1] < v <= a[i]``
    right   ``a[i-1] <= v < a[i]``
    ======  ============================
    
    Parameters
    ----------
    a : 1-D array_like
        Input array. If `sorter` is None, then it must be sorted in
        ascending order, otherwise `sorter` must be an array of indices
        that sort it.
    v : array_like
        Values to insert into `a`.
    side : {'left', 'right'}, optional
        If 'left', the index of the first suitable location found is g

In [25]:
a=np.arange(0,31,5)
a

array([ 0,  5, 10, 15, 20, 25, 30])

In [26]:
np.searchsorted(a,6)

2

In [28]:
#Binary search is used to find the required insertion points.
#  left , right 

a=np.arange(0,31,5)
np.searchsorted(a,6,side='right')

2

In [29]:
a=np.array([0,1,2,2,4,5,5,7,9])
a

array([0, 1, 2, 2, 4, 5, 5, 7, 9])

In [30]:
np.searchsorted(a,6)

7

In [31]:
a=np.array([0,1,2,5,14,15,15,17,19])
np.searchsorted(a,6)

4

In [32]:
np.searchsorted(a,6,side='right')

4

In [1]:
import numpy as np
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [2]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# insert 777 before index 2 

b= np.insert(a,2,777)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [0 1 2 3 4 5 6 7 8 9]
array  b 
 [  0   1 777   2   3   4   5   6   7   8   9]


In [4]:
#  here insert 777  before index 2  and index 5 
a=np.arange(10)
b=np.insert(a,[2,5],777)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [0 1 2 3 4 5 6 7 8 9]
array  b 
 [  0   1 777   2   3   4 777   5   6   7   8   9]


In [5]:
#  here insert 777  before index 2  and insert 888 before index 5 
a=np.arange(10)
b=np.insert(a,[2,5],[777,888])
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [0 1 2 3 4 5 6 7 8 9]
array  b 
 [  0   1 777   2   3   4 888   5   6   7   8   9]


In [7]:
#  here insert 777  before index 2  and insert 888 before index 5 
a=np.arange(10)
b=np.insert(a,[2,5,7],[777,888,999])
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [0 1 2 3 4 5 6 7 8 9]
array  b 
 [  0   1 777   2   3   4 888   5   6 999   7   8   9]


In [8]:
#  here insert 777  before index 2  and insert 888 before index 5 
a=np.arange(10)
b=np.insert(a,[2,5,7],[777,888])
print("array  a \n",a)
print("array  b \n",b)

ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (3,)

In [9]:
a=np.arange(10)
b=np.insert(a,2,4.67)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [0 1 2 3 4 5 6 7 8 9]
array  b 
 [0 1 4 2 3 4 5 6 7 8 9]


In [10]:
a=np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [11]:
b=np.insert(a,1,100)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [[10 20]
 [30 40]]
array  b 
 [ 10 100  20  30  40]


In [12]:
a=np.array([[10,20],[30,40]])
b=np.insert(a,1,100,axis=0)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [[10 20]
 [30 40]]
array  b 
 [[ 10  20]
 [100 100]
 [ 30  40]]


In [13]:
a=np.array([[10,20],[30,40]])
b=np.insert(a,1,100,axis=1)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [[10 20]
 [30 40]]
array  b 
 [[ 10 100  20]
 [ 30 100  40]]


In [14]:
a=np.array([[10,20],[30,40]])
b=np.insert(a,1,[[100,200],[300,400]],axis=0)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [[10 20]
 [30 40]]
array  b 
 [[ 10  20]
 [100 200]
 [300 400]
 [ 30  40]]


In [15]:
a=np.array([[10,20],[30,40]])
b=np.insert(a,1,[[100,200],[300,400]],axis=1)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [[10 20]
 [30 40]]
array  b 
 [[ 10 100 300  20]
 [ 30 200 400  40]]


In [16]:
help(np.append)

Help on function append in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    delete : Delet

In [17]:
a=np.arange(10)
b=np.append(a,100)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [0 1 2 3 4 5 6 7 8 9]
array  b 
 [  0   1   2   3   4   5   6   7   8   9 100]


In [18]:
a=np.arange(10)
b=np.append(a,2.5)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [0 1 2 3 4 5 6 7 8 9]
array  b 
 [0.  1.  2.  3.  4.  5.  6.  7.  8.  9.  2.5]


In [19]:
a=np.arange(10)
b=np.append(a,"2")
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [0 1 2 3 4 5 6 7 8 9]
array  b 
 ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '2']


In [20]:
a=np.arange(10)
b=np.append(a,"eswar")
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [0 1 2 3 4 5 6 7 8 9]
array  b 
 ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' 'eswar']


In [21]:
a=np.array([[10,20],[30,40]])
b=np.append(a,100)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [[10 20]
 [30 40]]
array  b 
 [ 10  20  30  40 100]


In [22]:
a=np.array([[10,20],[30,40]])
b=np.append(a,100,axis=0)
print("array  a \n",a)
print("array  b \n",b)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)

In [24]:
a=np.array([[10,20],[30,40]])
b=np.append(a,[[100,200]],axis=0)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [[10 20]
 [30 40]]
array  b 
 [[ 10  20]
 [ 30  40]
 [100 200]]


In [26]:
a=np.array([[10,20],[30,40]])
b=np.append(a,[[100],[200]],axis=1)
print("array  a \n",a)
print("array  b \n",b)

array  a 
 [[10 20]
 [30 40]]
array  b 
 [[ 10  20 100]
 [ 30  40 200]]


In [27]:
import numpy as np
help(np.delete)

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : slice, int or array of ints
        Indicate indices of sub-arrays to remove along the specified axis.
    
        .. versionchanged:: 1.19.0
            Boolean indices are now treated as a mask of elements to remove,
            rather than being cast to the integers 0 and 1.
    
    axis : int, optional
        The axis along which to delete the subarray defined by `obj`.
        If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also

In [28]:
a=np.arange(10,101,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [29]:
#  delete the element at 3rd index 
b=np.delete(a,3)
print("array a \n",a)
print("array b \n",b)

array a 
 [ 10  20  30  40  50  60  70  80  90 100]
array b 
 [ 10  20  30  50  60  70  80  90 100]


In [30]:
a=np.arange(10,101,10)
b=np.delete(a,[0,4,6])
print("array a \n",a)
print("array b \n",b)

array a 
 [ 10  20  30  40  50  60  70  80  90 100]
array b 
 [ 20  30  40  60  80  90 100]


In [ ]:
1 to 4 
a=np.arange(10,101,10)
b=np.delete(a,[1,2,3,4])
print("array a \n",a)
print("array b \n",b)


In [31]:
a=np.arange(10,101,10)
b=np.delete(a,range(1,5))
print("array a \n",a)
print("array b \n",b)

array a 
 [ 10  20  30  40  50  60  70  80  90 100]
array b 
 [ 10  60  70  80  90 100]


In [32]:
a=np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
b=np.delete(a,1)
print("array a \n",a)
print("array b \n",b)

array a 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b 
 [ 1  3  4  5  6  7  8  9 10 11 12]


In [34]:
a=np.arange(1,13).reshape(4,3)
b=np.delete(a,1,axis=0)
print("array a \n",a)
print("array b \n",b)

array a 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b 
 [[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [35]:
a=np.arange(1,13).reshape(4,3)
b=np.delete(a,1,axis=1)
print("array a \n",a)
print("array b \n",b)

array a 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b 
 [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


In [36]:
a=np.arange(1,13).reshape(4,3)
b=np.delete(a,[1,3],axis=0)
print("array a \n",a)
print("array b \n",b)

array a 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b 
 [[1 2 3]
 [7 8 9]]


In [37]:
a=np.arange(1,13).reshape(4,3)
b=np.delete(a,[1,3],axis=1)
print("array a \n",a)
print("array b \n",b)

IndexError: index 3 is out of bounds for axis 0 with size 3

In [38]:
a=np.arange(1,13).reshape(4,3)
b=np.delete(a,[1,2],axis=1)
print("array a \n",a)
print("array b \n",b)

array a 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b 
 [[ 1]
 [ 4]
 [ 7]
 [10]]


In [39]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [40]:
b=np.delete(a,1)
print("array a \n",a)
print("array b \n",b)

array a 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
array b 
 [ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [41]:
a=np.arange(24).reshape(2,3,4)
b=np.delete(a,1,axis=0)
print("array a \n",a)
print("array b \n",b)

array a 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
array b 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [43]:
a=np.arange(24).reshape(2,3,4)
b=np.delete(a,1,axis=1)
print("array a \n",a)
print("array b \n",b)

array a 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
array b 
 [[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [20 21 22 23]]]


In [44]:
a=np.arange(24).reshape(2,3,4)
b=np.delete(a,1,axis=2)
print("array a \n",a)
print("array b \n",b)

array a 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
array b 
 [[[ 0  2  3]
  [ 4  6  7]
  [ 8 10 11]]

 [[12 14 15]
  [16 18 19]
  [20 22 23]]]


In [1]:
import numpy as np
help(np.stack)

Help on function stack in module numpy:

stack(arrays, axis=0, out=None)
    Join a sequence of arrays along a new axis.
    
    The ``axis`` parameter specifies the index of the new axis in the
    dimensions of the result. For example, if ``axis=0`` it will be the first
    dimension and if ``axis=-1`` it will be the last dimension.
    
    .. versionadded:: 1.10.0
    
    Parameters
    ----------
    arrays : sequence of array_like
        Each array must have the same shape.
    
    axis : int, optional
        The axis in the result array along which the input arrays are stacked.
    
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what stack would have returned if no
        out argument were specified.
    
    Returns
    -------
    stacked : ndarray
        The stacked array has one more dimension than the input arrays.
    
    See Also
    --------
    concatenate : Join a sequenc

In [2]:
a=np.array([10,20,30])
b=np.array([40,50,60])
print(a)
print(b)

[10 20 30]
[40 50 60]


In [3]:
result = np.stack((a,b))
print("result  \n ",result)
print("result  \n ",result.shape)

result  
  [[10 20 30]
 [40 50 60]]
result  
  (2, 3)


In [4]:
result = np.stack((a,b),axis=1)
print("result  \n ",result)
print("result  \n ",result.shape)

result  
  [[10 40]
 [20 50]
 [30 60]]
result  
  (3, 2)


In [5]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [6]:
#  stack  axis= 0    number of 2d arrays 

result = np.stack((a,b))
print("result  \n ",result)
print("result  \n ",result.shape)

result  
  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
result  
  (2, 2, 3)


In [7]:
#  stack  axis= 0    number of 2d arrays 

result = np.stack((a,b),axis=1)
print("result  \n ",result)
print("result  \n ",result.shape)

result  
  [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
result  
  (2, 2, 3)


In [8]:
#  stack  axis= 0    number of 2d arrays 

result = np.stack((a,b),axis=2)
print("result  \n ",result)
print("result  \n ",result.shape)

result  
  [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
result  
  (2, 3, 2)


In [9]:
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b)

[[ 7  8  9]
 [10 11 12]]


In [11]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis

In [12]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis.
    s

In [13]:
a=np.array([10,20,30])
b=np.array([40,50,60])
result = np.vstack((a,b))
print("result \n",result)
print("shape  ",result.shape)

result 
 [[10 20 30]
 [40 50 60]]
shape   (2, 3)


In [14]:
a=np.array([10,20,30])
b=np.array([40,50,60,78,54])
result = np.vstack((a,b))
print("result \n",result)
print("shape  ",result.shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [15]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
result = np.vstack((a,b))
print("result \n",result)
print("shape  ",result.shape)

result 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape   (4, 3)


In [16]:
#  3d arrays 

a=np.arange(1,25).reshape(2,3,4)
b=np.arange(25,49).reshape(2,3,4)

print("array a \n",a)
print("array b \n",b)
result = np.vstack((a,b))

print("result array  \n",result)


array a 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
array b 
 [[[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]

 [[37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]
result array  
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]

 [[37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]


In [18]:
a=np.array([10,20,30])
b=np.array([40,50,60])
result = np.hstack((a,b))
print("result \n",result)
print("shape  ",result.shape)

#  stack 

result 
 [10 20 30 40 50 60]
shape   (6,)


In [19]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
result = np.hstack((a,b))
print("result \n",result)
print("shape  ",result.shape)

result 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
shape   (2, 6)


In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result = np.dstack((a,b))
print("result  \n",result)

result  
 [[[1 4]
  [2 5]
  [3 6]]]


In [21]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
result = np.dstack((a,b))
print("result \n",result)
print("shape  ",result.shape)

result 
 [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
shape   (2, 3, 2)


In [22]:
import numpy as np
help(np.split)

Help on function split in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arrays : list 

In [23]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
sub_ararys = np.split(a,3)
print("sub array  ",sub_ararys)

sub array   [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [25]:
a=np.arange(1,10)
sub_ararys = np.split(a,4)
print("sub array  ",sub_ararys)

ValueError: array split does not result in an equal division

In [26]:

# 2d arrays 
a=np.arange(1,25).reshape(6,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [27]:
result = np.split(a,3)
print(result)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]])]


In [28]:
result = np.split(a,2)
print(result)

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]


In [29]:
result = np.split(a,6)
print(result)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]]), array([[17, 18, 19, 20]]), array([[21, 22, 23, 24]])]


In [31]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [33]:
result = np.split(a,3,axis=1)
print(result)

ValueError: array split does not result in an equal division

In [32]:
result = np.split(a,2,axis=1)
print(result)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]


In [34]:
a=np.arange(10,101,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [35]:
result=np.split(a,[3,7])  #   0 to 3 ,  3 to 7 , 7 to ending
print(result)

[array([10, 20, 30]), array([40, 50, 60, 70]), array([ 80,  90, 100])]


In [36]:
a=np.arange(10,101,10)
result=np.split(a,[2,5,7])  #   0 to 2 ,  2 to 5 , 5 to 7,7 to ending
print(result)

[array([10, 20]), array([30, 40, 50]), array([60, 70]), array([ 80,  90, 100])]


In [37]:
a=np.arange(1,13).reshape(6,2)
result = np.split(a,[3,4])  
#     0 to 3  , 3 to 4  just 3rd row , 4 to ending
print(result)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [38]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [39]:
a=np.arange(1,19).reshape(3,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [40]:
result = np.split(a,[1,3,5],axis=1)  
#  0 to 1  ,  1 to 3  , 3 to 5 , 5 to ending 
print(result)

[array([[ 1],
       [ 7],
       [13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]]), array([[ 6],
       [12],
       [18]])]


In [41]:
result = np.split(a,[1,3,3],axis=1)  
#  0 to 1  ,  1 to 3  , 3 to 3 , 3 to ending 
print(result)

[array([[ 1],
       [ 7],
       [13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([], shape=(3, 0), dtype=int32), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])]


In [42]:
help(np.vsplit)

Help on function vsplit in module numpy:

vsplit(ary, indices_or_sections)
    Split an array into multiple sub-arrays vertically (row-wise).
    
    Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
    to ``split`` with `axis=0` (default), the array is always split along the
    first axis regardless of the array dimension.
    
    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(16.0).reshape(4, 4)
    >>> x
    array([[ 0.,   1.,   2.,   3.],
           [ 4.,   5.,   6.,   7.],
           [ 8.,   9.,  10.,  11.],
           [12.,  13.,  14.,  15.]])
    >>> np.vsplit(x, 2)
    [array([[0., 1., 2., 3.],
           [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]])]
    >>> np.vsplit(x, np.array([3, 6]))
    [array([[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]]), arr

In [43]:
a=np.arange(1,13).reshape(6,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [44]:
result = np.vsplit(a,2)
print(result)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


In [45]:
result = np.vsplit(a,3)
print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [46]:
result = np.vsplit(a,6)
print(result)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [47]:
result = np.vsplit(a,[2,4])
print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [48]:
a=np.arange(1,13).reshape(3,4)
result = np.hsplit(a,2)
print(result)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [49]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
a=np.arange(24).reshape(4,6)
result = np.hsplit(a,[2,4])
# 0 to 2 columns  2 to 4 , 4 to ending 
print(result)

[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])]


In [51]:
help(np.dsplit)

Help on function dsplit in module numpy:

dsplit(ary, indices_or_sections)
    Split array into multiple sub-arrays along the 3rd axis (depth).
    
    Please refer to the `split` documentation.  `dsplit` is equivalent
    to `split` with ``axis=2``, the array is always split along the third
    axis provided the array dimension is greater than or equal to 3.
    
    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(16.0).reshape(2, 2, 4)
    >>> x
    array([[[ 0.,   1.,   2.,   3.],
            [ 4.,   5.,   6.,   7.]],
           [[ 8.,   9.,  10.,  11.],
            [12.,  13.,  14.,  15.]]])
    >>> np.dsplit(x, 2)
    [array([[[ 0.,  1.],
            [ 4.,  5.]],
           [[ 8.,  9.],
            [12., 13.]]]), array([[[ 2.,  3.],
            [ 6.,  7.]],
           [[10., 11.],
            [14., 15.]]])]
    >>> np.dsplit(x, np.array([3, 6]))
    [array([[[ 0.,   1.,   2.],
          

In [52]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
np.split(a,2)

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])]

In [54]:
#
np.split(a,[1,3])

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([], shape=(0, 3, 4), dtype=int32)]

In [55]:
a=np.arange(1,10)
sub_ararys = np.split(a,4)
print("sub array  ",sub_ararys)

ValueError: array split does not result in an equal division

In [56]:
a=np.arange(1,10)
sub_ararys = np.array_split(a,4)
print("sub array  ",sub_ararys)

sub array   [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [1]:
import numpy as np
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [2]:
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])
print("array  a \n ",a)
print("array  b \n ",b)
elem = a*b
print(" array  \n ",elem)

array  a 
  [[10 20]
 [30 40]]
array  b 
  [[1 2]
 [3 4]]
 array  
  [[ 10  40]
 [ 90 160]]


In [3]:
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])
print("array  a \n ",a)
print("array  b \n ",b)
matrix_mult = np.dot(a,b)
print(" array  \n ",matrix_mult)


array  a 
  [[10 20]
 [30 40]]
array  b 
  [[1 2]
 [3 4]]
 array  
  [[ 70 100]
 [150 220]]


In [4]:
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])
print("array  a \n ",a)
print("array  b \n ",b)
matrix_mult = a.dot(b)
print(" array  \n ",matrix_mult)

array  a 
  [[10 20]
 [30 40]]
array  b 
  [[1 2]
 [3 4]]
 array  
  [[ 70 100]
 [150 220]]


In [7]:
import numpy as np
help(np.matrix)


Help on class matrix in module numpy:

class matrix(ndarray)
 |  matrix(data, dtype=None, copy=True)
 |  
 |  matrix(data, dtype=None, copy=True)
 |  
 |  .. note:: It is no longer recommended to use this class, even for linear
 |            algebra. Instead use regular arrays. The class may be removed
 |            in the future.
 |  
 |  Returns a matrix from an array-like object, or from a string of data.
 |  A matrix is a specialized 2-D array that retains its 2-D nature
 |  through operations.  It has certain special operators, such as ``*``
 |  (matrix multiplication) and ``**`` (matrix power).
 |  
 |  Parameters
 |  ----------
 |  data : array_like or string
 |     If `data` is a string, it is interpreted as a matrix with commas
 |     or spaces separating columns, and semicolons separating rows.
 |  dtype : data-type
 |     Data-type of the output matrix.
 |  copy : bool
 |     If `data` is already an `ndarray`, then this flag determines
 |     whether the data is copied (the 

In [8]:
a=np.matrix('10 20 30;40 50 60')
b=np.matrix('10,20,30;40,50,60')
print("type a  ",type(a))
print("type b  ",type(b))

print(" matrix  a \n ",a)
print(" matrix  b \n ",b)

type a   <class 'numpy.matrix'>
type b   <class 'numpy.matrix'>
 matrix  a 
  [[10 20 30]
 [40 50 60]]
 matrix  b 
  [[10 20 30]
 [40 50 60]]


In [9]:
a=np.matrix([[10,20,30],[40,50,60]])
print("type a  ",type(a))
print(" matrix  a \n ",a)


type a   <class 'numpy.matrix'>
 matrix  a 
  [[10 20 30]
 [40 50 60]]


In [10]:
a=np.arange(6).reshape(3,2)
b=np.matrix(a)
print("type a  ",type(b))
print(" matrix  a \n ",b)


type a   <class 'numpy.matrix'>
 matrix  a 
  [[0 1]
 [2 3]
 [4 5]]


In [11]:
a= np.array([[1,2],[3,4]])
b= np.matrix([[1,2],[3,4]])
print("addition array is \n ",a+a)
print("addition matrix is \n ",b+b)

addition array is 
  [[2 4]
 [6 8]]
addition matrix is 
  [[2 4]
 [6 8]]


In [12]:
a= np.array([[1,2],[3,4]])
b= np.matrix([[1,2],[3,4]])
print("addition array is \n ",a*a)
print("addition matrix is \n ",b*b)

addition array is 
  [[ 1  4]
 [ 9 16]]
addition matrix is 
  [[ 7 10]
 [15 22]]


In [14]:
a= np.array([[1,2],[3,4]])
b= np.matrix([[1,2],[3,4]])
print("addition array is \n ",a**2)
print("addition matrix is \n ",b**2)

addition array is 
  [[ 1  4]
 [ 9 16]]
addition matrix is 
  [[ 7 10]
 [15 22]]


In [15]:
a= np.array([[1,2],[3,4]])
b= np.matrix([[1,2],[3,4]])
print("array a is \n ",a)
print("matrix is \n ",b)
array_t = a.T
matrix_t = b.T
print("array a is \n ",array_t)
print("matrix is \n ",matrix_t)

array a is 
  [[1 2]
 [3 4]]
matrix is 
  [[1 2]
 [3 4]]
array a is 
  [[1 3]
 [2 4]]
matrix is 
  [[1 3]
 [2 4]]
